## Student Attendance Analytics with Pandas

In [ ]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [9]:
df = pd.read_excel("database/aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
import pandas as pd

df = pd.read_excel("database/aiml_attendance.xlsx")

print("First 10 rows:")
display(df.head(10))

print("Shape of the DataFrame:")
print(df.shape)

print("Data types of each column:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1

Shape of the DataFrame:
(59, 12)
Data types of each column:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
print("Missing values in each column:")
print(df.isnull().sum())

print("\nColumns with null values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nCount of 'Never' in Last Present Date:")
print(df["Last Present Date"].astype(str).str.strip().eq("Never").sum())

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Columns with null values:
Series([], dtype: int64)

Count of 'Never' in Last Present Date:
2

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
import re

df.columns = [
    re.sub(r'[^a-zA-Z0-9]+', '_', col.strip()).strip('_').lower()
    for col in df.columns
]

print("Updated column list:")
print(df.columns.tolist())

Updated column list:
['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

In [11]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""

print(df.columns.tolist())

attendance_col = next(col for col in df.columns if 'attendance' in col.lower())
date_col = next(col for col in df.columns if 'last present date' in col.lower().replace('_', ' '))

df[attendance_col] = pd.to_numeric(
    df[attendance_col].astype(str).str.replace('%', '', regex=False),
    errors='coerce'
)

df[date_col] = pd.to_datetime(
    df[date_col].replace('Never', pd.NaT),
    errors='coerce'
)

print(df.dtypes)
display(df.head())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']
roll_no                            str
student_name                       str
subject                            str
total_classes                    int64
present                          int64
absent                           int64
excused                          int64
attendance                       int64
status                             str
classes_needed_75                  str
last_present_date       datetime64[us]
consecutive_absences             int64
dtype: object

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance,status,classes_needed_75,last_present_date,consecutive_absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1

#### Section 2: Filtering & Selection

In [13]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""

print(df.columns.tolist())

status_col = next(col for col in df.columns if col.strip().lower() == "status")
attendance_col = next(col for col in df.columns if "attendance" in col.strip().lower())

critical_students = df[
    df[status_col].astype(str).str.strip().str.lower() == "critical"
].sort_values(by=attendance_col, ascending=True)

display(critical_students)

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance,status,classes_needed_75,last_present_date,consecutive_absences
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0,Critical,36 more,NaT,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0,Critical,36 more,NaT,12
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-09-22,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-09-08,9
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-10-06,2
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-09-08,9
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-10-06,2
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-09-22,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-09-29,3
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33,Critical,20 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33,Critical,20 more,2026-10-06,2
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42,Critical,16 more,2026-10-06,2
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50,Critical,12 more,2026-10-09,1
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50,Critical,12 more,2026-10-06,2
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58,Critical,8 more,2026-09-25,4
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-10,0

In [18]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""

print(df.columns.tolist())

fully_absent = df[pd.to_numeric(df["present"], errors="coerce") == 0]

print("Students with 0 present days:")
display(fully_absent[["roll_no", "student_name", "consecutive_absences"]])

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']
Students with 0 present days:

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [19]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """

print("All Safe students using .loc:")
display(df.loc[df["status"].str.strip().str.lower() == "safe"])

print("First 15 rows and columns 2-6 using .iloc:")
display(df.iloc[:15, 1:6])

All Safe students using .loc:

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance,status,classes_needed_75,last_present_date,consecutive_absences
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100,Safe,✓ Met,2026-10-10,0
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0

First 15 rows and columns 2-6 using .iloc:

,student_name,subject,total_classes,present,absent
0,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4
1,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4
2,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11
3,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1
4,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
5,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2
6,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
7,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0
8,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
9,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3
10,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3
11,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3
12,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6
13,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3
14,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1

In [20]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""

students = df[pd.to_numeric(df["consecutive_absences"], errors="coerce") >= 5]

print("Students with 5 or more consecutive absences:")
display(students[["student_name", "status", "last_present_date"]])

Students with 5 or more consecutive absences:

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [21]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""

status_summary = df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

print("Summary by Status:")
display(status_summary)

Summary by Status:

          student_count  average_attendance  max_consecutive_absences
status
Critical             23           30.086957                        12
Safe                 13           93.230769                         1
Warning              23           80.565217                         2

In [22]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""

df["attendance"] = pd.to_numeric(
    df["attendance"].astype(str).str.replace("%", "", regex=False),
    errors="coerce"
)

df["Attendance Category"] = pd.cut(
    df["attendance"],
    bins=[-float("inf"), 60, 75, 90, float("inf")],
    labels=["Poor", "Average", "Good", "Excellent"],
    right=False
)

df["Attendance Category"] = df["Attendance Category"].replace({
    "Good": "Good",
    "Average": "Average"
})

print("Student count in each Attendance Category:")
display(df.groupby("Attendance Category", observed=False)["student_name"].count())

Student count in each Attendance Category:

Attendance Category
Poor         20
Average       3
Good         23
Excellent    13
Name: student_name, dtype: int64

In [23]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""

totals = df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})

print("Total classes conducted, present count, and absent count:")
display(totals)

Total classes conducted, present count, and absent count:

total_classes    708
present          451
absent           257
dtype: int64

In [24]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""

status_summary = df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum")
)

display(status_summary)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8      3.608696         193
Safe               11           12     11.153846          11
Warning             9           10      9.695652          53

### Section 4: Feature Engineering & Transformation

In [25]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""

df["risk_score"] = (
    df["absent"] * 0.4
    + df["consecutive_absences"] * 0.6
)

top_10_risk = df.sort_values(
    by="risk_score",
    ascending=False
).head(10)

print("Top 10 students with the highest risk score:")
display(top_10_risk[["roll_no", "student_name", "absent", "consecutive_absences", "risk_score"]])

Top 10 students with the highest risk score:

,roll_no,student_name,absent,consecutive_absences,risk_score
33,4MW24AI036,RAJU ASHOKA RATHOD,12,12,12.0
32,4MW24AI035,RAJATH K K,12,12,12.0
58,4MW25AI401,Omkar Rane,11,9,9.8
41,4MW24AI045,SHRAVYA,10,9,9.4
2,4MW24AI003,ADITYA,11,5,7.4
25,4MW24AI028,MOURYA RAJ H N,9,5,6.6
35,4MW24AI038,RASHMI,11,2,5.6
18,4MW24AI021,KISHAN J,9,3,5.4
22,4MW24AI025,MANMITHA,10,2,5.2
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),10,2,5.2

In [27]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""

df["classes_needed_numeric"] = (
    df["classes_needed_75"]
    .astype(str)
    .str.extract(r"(\d+)", expand=False)
    .fillna("0")
    .astype(int)
)

display(df[["student_name", "classes_needed_75", "classes_needed_numeric"]])

,student_name,classes_needed_75,classes_needed_numeric
0,ABHIJITH,4 more,4
1,ABHISHEK KRISHNA P,4 more,4
2,ADITYA,32 more,32
3,AKSHATA JAKAREDDY,✓ Met,0
4,ANANYA,✓ Met,0
5,ANANYASHREE,✓ Met,0
6,ANKITA TARANATH MESTA,✓ Met,0
7,ANVITH S SHERIGAR,✓ Met,0
8,APEKSHA,✓ Met,0
9,ARLENE VELORA FERNANDES,✓ Met,0
10,ASHRITHA,✓ Met,0
11,AYESHA REEMAN,✓ Met,0
12,DHANRAJ L POOJARY,12 more,12
13,DHANYATHA R,✓ Met,0
14,G BHUPATHE,✓ Met,0
15,HARSHAL G POOJARY,✓ Met,0
16,JNANESH . S,✓ Met,0
17,KEERTHAN KRISHNA SHERIGAR,✓ Met,0
18,KISHAN J,24 more,24
19,KUNDAR KASHISH CHANDRA,✓ Met,0
20,LAKSHITHA,✓ Met,0
21,MANEESH SHETTY,✓ Met,0
22,MANMITHA,28 more,28
23,MAYUR,✓ Met,0
24,MOHAMMED SIMAK,✓ Met,0
25,MOURYA RAJ H N,24 more,24
26,MUHAMMED NASHIT,✓ Met,0
27,NAVYA,24 more,24
28,PAVITHRA NAYAK,✓ Met,0
29,PRAGNYA R,✓ Met,0
30,PRAMOD ACHAR,24 more,24
31,RAJATH H S,24 more,24
32,RAJATH K K,36 more,36
33,RAJU ASHOKA RATHOD,36 more,36
34,RAKESH HEGDE,✓ Met,0
35,RASHMI,32 more,32
36,RITHIN,20 more,20
37,SANIKA,24 more,24
38,SHAMANTH K,✓ Met,0
39,SHETTY RASHIK RATHNAKAR,16 more,16
40,SHODAN B POOJARY,✓ Met,0
41,SHRAVYA,28 more,28
42,SHREESH A DEVADIGA,✓ Met,0
43,SHRIYA DEVADIGA,✓ Met,0
44,SINCHANA (SUNDARA MADIVALA),28 more,28
45,SINCHANA (MURALI KUPPAYYA MOGAVEERA),✓ Met,0
46,SPOORTHI,✓ Met,0
47,SUPRAJA S M,12 more,12
48,SUPRITHA,✓ Met,0
49,TEJAS,✓ Met,0
50,TRIPTHI H PADMASHALI,✓ Met,0
51,VAMSH,20 more,20
52,VANDANA,✓ Met,0
53,VIGNESH ADIGA,8 more,8
54,VIHAAN S,4 more,4
55,YASHASVI K POOJARY,✓ Met,0
56,Raksha,✓ Met,0
57,Dhananjay,✓ Met,0
58,Omkar Rane,32 more,32

In [28]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """

df["Attendance Flag"] = df["attendance"].apply(
    lambda x: "Defaulter" if x < 75 else "Safe"
)

display(df[["student_name", "attendance", "Attendance Flag"]])

                            student_name  attendance Attendance Flag
0                               ABHIJITH          67       Defaulter
1                     ABHISHEK KRISHNA P          67       Defaulter
2                                 ADITYA           8       Defaulter
3                      AKSHATA JAKAREDDY          92            Safe
4                                 ANANYA          83            Safe
5                            ANANYASHREE          83            Safe
6                  ANKITA TARANATH MESTA          83            Safe
7                      ANVITH S SHERIGAR         100            Safe
8                                APEKSHA          83            Safe
9                ARLENE VELORA FERNANDES          75            Safe
10                              ASHRITHA          75            Safe
11                         AYESHA REEMAN          75            Safe
12                     DHANRAJ L POOJARY          50       Defaulter
13                           DHANYATHA R          75            Safe
14                            G BHUPATHE          92            Safe
15                     HARSHAL G POOJARY          92            Safe
16                           JNANESH . S          92            Safe
17             KEERTHAN KRISHNA SHERIGAR          92            Safe
18                              KISHAN J          25       Defaulter
19                KUNDAR KASHISH CHANDRA          83            Safe
20                             LAKSHITHA          83            Safe
21                        MANEESH SHETTY          92            Safe
22                              MANMITHA          17       Defaulter
23                                 MAYUR          83            Safe
24                        MOHAMMED SIMAK          75            Safe
25                        MOURYA RAJ H N          25       Defaulter
26                       MUHAMMED NASHIT          92            Safe
27                                 NAVYA          25       Defaulter
28                        PAVITHRA NAYAK          83            Safe
29                             PRAGNYA R          92            Safe
30                          PRAMOD ACHAR          25       Defaulter
31                            RAJATH H S          25       Defaulter
32                            RAJATH K K           0       Defaulter
33                    RAJU ASHOKA RATHOD           0       Defaulter
34                          RAKESH HEGDE          83            Safe
35                                RASHMI           8       Defaulter
36                                RITHIN          33       Defaulter
37                                SANIKA          25       Defaulter
38                            SHAMANTH K          92            Safe
39               SHETTY RASHIK RATHNAKAR          42       Defaulter
40                      SHODAN B POOJARY          75            Safe
41                               SHRAVYA          17       Defaulter
42                    SHREESH A DEVADIGA         100            Safe
43                       SHRIYA DEVADIGA          92            Safe
44           SINCHANA (SUNDARA MADIVALA)          17       Defaulter
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)          92            Safe
46                              SPOORTHI          83            Safe
47                           SUPRAJA S M          50       Defaulter
48                              SUPRITHA          83            Safe
49                                 TEJAS          83            Safe
50                  TRIPTHI H PADMASHALI          75            Safe
51                                 VAMSH          33       Defaulter
52                               VANDANA          83            Safe
53                         VIGNESH ADIGA          58       Defaulter
54                              VIHAAN S          67       Defaulter
55                    YASHASVI K POOJARY          83            Safe
56                                Raksha          83            Safe
57                             Dhananjay          83            Safe
58                            Omkar Rane           8       Defaulter

In [29]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""

df["Attendance Range"] = pd.cut(
    df["attendance"],
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True
)

display(df[["student_name", "attendance", "Attendance Range"]])

                            student_name  attendance Attendance Range
0                               ABHIJITH          67          Warning
1                     ABHISHEK KRISHNA P          67          Warning
2                                 ADITYA           8         Critical
3                      AKSHATA JAKAREDDY          92        Excellent
4                                 ANANYA          83             Good
5                            ANANYASHREE          83             Good
6                  ANKITA TARANATH MESTA          83             Good
7                      ANVITH S SHERIGAR         100        Excellent
8                                APEKSHA          83             Good
9                ARLENE VELORA FERNANDES          75          Warning
10                              ASHRITHA          75          Warning
11                         AYESHA REEMAN          75          Warning
12                     DHANRAJ L POOJARY          50         Critical
13                           DHANYATHA R          75          Warning
14                            G BHUPATHE          92        Excellent
15                     HARSHAL G POOJARY          92        Excellent
16                           JNANESH . S          92        Excellent
17             KEERTHAN KRISHNA SHERIGAR          92        Excellent
18                              KISHAN J          25         Critical
19                KUNDAR KASHISH CHANDRA          83             Good
20                             LAKSHITHA          83             Good
21                        MANEESH SHETTY          92        Excellent
22                              MANMITHA          17         Critical
23                                 MAYUR          83             Good
24                        MOHAMMED SIMAK          75          Warning
25                        MOURYA RAJ H N          25         Critical
26                       MUHAMMED NASHIT          92        Excellent
27                                 NAVYA          25         Critical
28                        PAVITHRA NAYAK          83             Good
29                             PRAGNYA R          92        Excellent
30                          PRAMOD ACHAR          25         Critical
31                            RAJATH H S          25         Critical
32                            RAJATH K K           0         Critical
33                    RAJU ASHOKA RATHOD           0         Critical
34                          RAKESH HEGDE          83             Good
35                                RASHMI           8         Critical
36                                RITHIN          33         Critical
37                                SANIKA          25         Critical
38                            SHAMANTH K          92        Excellent
39               SHETTY RASHIK RATHNAKAR          42         Critical
40                      SHODAN B POOJARY          75          Warning
41                               SHRAVYA          17         Critical
42                    SHREESH A DEVADIGA         100        Excellent
43                       SHRIYA DEVADIGA          92        Excellent
44           SINCHANA (SUNDARA MADIVALA)          17         Critical
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)          92        Excellent
46                              SPOORTHI          83             Good
47                           SUPRAJA S M          50         Critical
48                              SUPRITHA          83             Good
49                                 TEJAS          83             Good
50                  TRIPTHI H PADMASHALI          75          Warning
51                                 VAMSH          33         Critical
52                               VANDANA          83             Good
53                         VIGNESH ADIGA          58          Warning
54                              VIHAAN S          67          Warning
55                    YASHASVI K POOJARY          83             Good
56                                Raksha          83             Good
57                             Dhananjay          83             Good
58                            Omkar Rane           8         Critical

### Section 5: Advanced Analysis

In [30]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""

pivot_summary = pd.pivot_table(
    df,
    index="status",
    columns="Attendance Category",
    values="student_name",
    aggfunc="count",
    fill_value=0,
    observed=False
)

print("Count of students by Status and Attendance Category:")
display(pivot_summary)

Count of students by Status and Attendance Category:

Attendance Category  Poor  Average  Good  Excellent
status
Critical               20        3     0          0
Safe                    0        0     0         13
Warning                 0        0    23          0

In [31]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""

df["base_name"] = df["student_name"].str.replace(r"\s*\d+$", "", regex=True).str.strip().str.upper()

duplicate_names = df[df.duplicated(subset="base_name", keep=False)].sort_values("base_name")

display(duplicate_names)

Empty DataFrame
Columns: [roll_no, student_name, subject, total_classes, present, absent, excused, attendance, status, classes_needed_75, last_present_date, consecutive_absences, Attendance Category, risk_score, classes_needed_numeric, Attendance Flag, Attendance Range, base_name]
Index: []

In [32]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""

student_details = pd.DataFrame({
    "roll_no": df["roll_no"].unique(),
    "branch": ["AIML"] * df["roll_no"].nunique(),
    "semester": [5] * df["roll_no"].nunique()
})

merged_df = pd.merge(
    df,
    student_details,
    on="roll_no",
    how="inner"
)

print("Merged Student Data:")
display(merged_df)

Merged Student Data:

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance,status,classes_needed_75,last_present_date,consecutive_absences,Attendance Category,risk_score,classes_needed_numeric,Attendance Flag,Attendance Range,base_name,branch,semester
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHIJITH,AIML,5
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHISHEK KRISHNA P,AIML,5
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-09-22,5,Poor,7.4,32,Defaulter,Critical,ADITYA,AIML,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,AKSHATA JAKAREDDY,AIML,5
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYA,AIML,5
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYASHREE,AIML,5
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANKITA TARANATH MESTA,AIML,5
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100,Safe,✓ Met,2026-10-10,0,Excellent,0.0,0,Safe,Excellent,ANVITH S SHERIGAR,AIML,5
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,APEKSHA,AIML,5
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,ARLENE VELORA FERNANDES,AIML,5
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,ASHRITHA,AIML,5
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-06,2,Good,2.4,0,Safe,Warning,AYESHA REEMAN,AIML,5
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50,Critical,12 more,2026-10-06,2,Poor,3.6,12,Defaulter,Critical,DHANRAJ L POOJARY,AIML,5
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,DHANYATHA R,AIML,5
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,G BHUPATHE,AIML,5
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,HARSHAL G POOJARY,AIML,5
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,JNANESH . S,AIML,5
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,KEERTHAN KRISHNA SHERIGAR,AIML,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-09-29,3,Poor,5.4,24,Defaulter,Critical,KISHAN J,AIML,5
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-10,0,Good,0.8,0,Safe,Good,KUNDAR KASHISH CHANDRA,AIML,5
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-10,0,Good,0.8,0,Safe,Good,LAKSHITHA,AIML,5
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,MANEESH SHETTY,AIML,5
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,MANMITHA,AIML,5
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,MAYUR,AIML,5
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-06,2,Good,2.4,0,Safe,Warning,MOHAMMED SIMAK,AIML,5
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-09-22,5,Poor,6.6,24,Defaulter,Critical,MOURYA RAJ H N,AIML,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,MUHAMMED NASHIT,AIML,5
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,NAVYA,AIML,5
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,PAVITHRA NAYAK,AIML,5
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,PRAGNYA R,AIML,5
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,PRAMOD ACHAR,AIML,5
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,RAJATH H S,AIML,5
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,RAJATH K K,AIML,5
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,RAJU ASHOKA RATHOD,AIML,5
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,RAKESH HEGDE,AIML,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-10-06,2,Poor,5.6,32,Defaulter,Critical,RASHMI,AIML,5
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,RITHIN,AIML,5
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,SANIKA,AIML,5
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,SHAMANTH K,AIML,5
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42,Critical,16 more,2026-10-06,2,Poor,4.0,16,Defaulter,Critical,SHETTY RASHIK RATHNAKAR,AIML,5
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-10,0,Good,1.2,0,Safe,Warning,SHODAN B POOJARY,AIML,5
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-09-08,9,Poor,9.4,28,Defaulter,Critical,SHRAVYA,AIML,5
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100,Safe,✓ Met,2026-10-10,0,Excellent,0.0,0,Safe,Excellent,SHREESH A DEVADIGA,AIML,5
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SHRIYA DEVADIGA,AIML,5
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA (SUNDARA MADIVALA),AIML,5
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SINCHANA (MURALI KUPPAYYA MOGAVEERA),AIML,5
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,SPOORTHI,AIML,5
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50,Critical,12 more,2026-10-09,1,Poor,3.0,12,Defaulter,Critical,SUPRAJA S M,AIML,5
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,SUPRITHA,AIML,5
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,TEJAS,AIML,5
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,TRIPTHI H PADMASHALI,AIML,5
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,VAMSH,AIML,5
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,VANDANA,AIML,5
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58,Critical,8 more,2026-09-25,4,Poor,4.4,8,Defaulter,Warning,VIGNESH ADIGA,AIML,5
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67,Critical,4 more,2026-10-10,0,Average,1.6,4,Defaulter,Warning,VIHAAN S,AIML,5
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,YASHASVI K POOJARY,AIML,5
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,RAKSHA,AIML,5
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,DHANANJAY,AIML,5
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8,Critical,32 more,2026-09-08,9,Poor,9.8,32,Defaulter,Critical,OMKAR RANE,AIML,5

In [33]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""

critical_students = df[df["status"].str.strip().str.lower() == "critical"]
critical_students.to_csv("critical_students.csv", index=False)

status_summary = df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)
status_summary.to_csv("status_summary.csv")

top_10_risk = df.sort_values(by="risk_score", ascending=False).head(10)
top_10_risk.to_csv("top_10_risk_score.csv", index=False)

print("CSV files exported successfully:")
print("1. critical_students.csv")
print("2. status_summary.csv")
print("3. top_10_risk_score.csv")

CSV files exported successfully:
1. critical_students.csv
2. status_summary.csv
3. top_10_risk_score.csv